# Generated by Django 4.0.3 on 2022-03-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_employee_options_alter_department_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
